name: Publish NuGet Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install PowerShell (Required for Increment-Version.ps1)
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell
        pwsh --version  # Verify PowerShell is installed

    - name: Debugging - List Files Before Running Script
      run: ls -la

    - name: Run Increment-Version.ps1 (Ensure Correct Directory)
      run: |
        cd CoreLibrary
        pwsh -File Increment-Version.ps1

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Pack NuGet Package
      run: dotnet pack --no-build --configuration Release CoreLibrary/CoreLibrary.csproj

    - name: Push to GitHub Packages
      run: dotnet nuget push "./CoreLibrary/bin/Release/*.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}"
